name: Version Tag Docker Image
description: Create semver tags for an existing Docker image (e.g. v0, v0.1, v0.1.2), utilizing info from release-please pull requests.
branding:
  icon: arrow-up-right
  color: blue

inputs:
  image:
    description: Name of the docker image (e.g. `"my-namespace/my-image"`)
    required: true
  version:
    description: "Manually provided semantic version (e.g: 0.3.4)"
    required: true
  registry:
    description: Docker registry
    required: true
  username:
    description: Docker username
    required: true
  password:
    description: Docker password
    required: true
  add-pr-label:
    description: 'Add label `"version tagged: $inputs.registry"` to the relevant release-please created pull request'
    required: true
    default: "true"
  pr-label-color:
    description: PR label color
    required: true
    default: "#0db7ed"
  token:
    description: Token for interacting with the Github API. Default to using the special GITHUB_TOKEN. Because of limitations imposed by GitHub, this must be set if you want the setting of the PR label to trigger an event.
    required: true
    default: ${{ github.token }}

outputs:
  version:
    description: The version that was passed in to the action
    value: ${{ inputs.version }}
  commit-sha:
    description: Commit SHA that correlates to this version
    value: ${{ steps.release_pr.outputs.commit-sha }}
  pr-number:
    description: PR number that correlates to this version
    value: ${{ steps.release_pr.outputs.pr-number }}

runs:
  using: composite
  # permissions:
  #   contents: read
  #   pull-requests: write
  #   # TODO: Remove `issues: read` and `repository-projects: read` once
  #   #       https://github.com/cli/cli/pull/4876 has been resolved.
  #   #       More info here:
  #   #       https://github.com/cli/cli/discussions/5307#discussioncomment-2358577
  #   issues: read
  #   repository-projects: read
  steps:
    - uses: actions/checkout@v3

    - uses: apexskier/github-semver-parse@v1
      id: semver
      with:
        version: ${{ inputs.version }}

    - name: Get release pull request info
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        VERSION: ${{ inputs.version }}
      id: release_pr
      run: |

        gh pr list \
          --search "in:title chore(main): release $VERSION" \
          --limit 1 \
          --state merged \
          --json number,mergeCommit \
          --jq '.[0]' > pr.json

        if [[ $DEBUG == 'true' ]]; then
          cat pr.json
        fi

        PR_NUMBER=$(jq -r .number pr.json)
        COMMIT_SHA=$(jq -r .mergeCommit.oid pr.json)

        if [[ -z "$PR_NUMBER" ]]; then
          echo "::error Failed to find corresponding release-please created pull request for version ${{ inputs.version }}" \
          exit 1
        fi
        if [[ -z "$COMMIT_SHA" ]]; then
          echo "::error Failed to find mergeCommit.oid / SHA for pull request $PR_NUMBER" \
          exit 1
        fi

        echo pr-number=$PR_NUMBER >> $GITHUB_OUTPUT
        echo commit-sha=$COMMIT_SHA >> $GITHUB_OUTPUT

    - name: Print context
      if: ${{ env.DEBUG == 'true' }}
      shell: bash
      run: |
        echo 'github: ${{ toJSON(github) }}'
        echo 'job: ${{ toJSON(job) }}'
        echo 'steps: ${{ toJSON(steps) }}'
        echo 'runner: ${{ toJSON(runner) }}'
        echo 'strategy: ${{ toJSON(strategy) }}'
        echo 'matrix: ${{ toJSON(matrix) }}'

    - name: Log in to Docker registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push Docker version tags
      uses: akhilerm/tag-push-action@v2.0.0
      env:
        DOCKER_IMAGE: ${{ inputs.registry }}/${{ inputs.image }}
      with:
        src: ${{ env.DOCKER_IMAGE }}:${{ steps.release_pr.outputs.commit-sha }}
        dst: |
          ${{ env.DOCKER_IMAGE }}:${{ inputs.version }}
          ${{ env.DOCKER_IMAGE }}:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
          ${{ env.DOCKER_IMAGE }}:${{ steps.semver.outputs.major }}

    - name: Add label and comment to pull request regarding the new Docker tags
      shell: bash
      if: ${{ inputs.add-pr-label == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        LABEL: "version tagged: ${{ inputs.registry }}"
        LABEL_COLOR: "${{ inputs.pr-label-color }}"
        DOCKER_IMAGE: ${{ inputs.registry }}/${{ inputs.image }}
      run: |
        gh label create "$LABEL" \
          --force \
          --color "$LABEL_COLOR" \
          --description "Version tags have been pushed to this Docker repository"
        gh pr edit "${{ steps.release_pr.outputs.pr-number }}" --add-label "$LABEL"
        gh pr comment "${{ steps.release_pr.outputs.pr-number }}" \
        --body "The following Docker tags have been created:
        * $DOCKER_IMAGE:${{ inputs.version }}
        * $DOCKER_IMAGE:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
        * $DOCKER_IMAGE:${{ steps.semver.outputs.major }}"
