on:
  push:
    branches:
      - main

env:
  ACTION_NAME: version-tag-docker-image

name: Main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    name: Test action
    env:
      DEBUG: "true"
      DRY_RUN: "true"
    steps:
      - uses: actions/checkout@v3
      # - name: Run action
      #   uses: ./
      #   with:
      #     version: "0.1.2"
      #     docker-registry: jacobsvante
      #     docker-username: integrationtester
      #     docker-password: ${{ secrets.DOCKER_PASSWORD }}
      #     docker-image: version-tag-docker-image-action-tester

  release-please:
    runs-on: ubuntu-latest
    needs: [pre-commit, test]
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: ${{ env.ACTION_NAME }}
          bump-minor-pre-major: true
      - uses: actions/checkout@v3
      - name: Tag major and minor versions in Git
        if: ${{ steps.release.outputs.release_created }}
        uses: jacobsvante/tag-major-minor-action@v0
        with:
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}
